apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autoguard.fullname" . }}-config
  labels:
    {{- include "autoguard.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
