apiVersion: v2
name: autoguard
description: AutoGuard AI – Real-Time Autonomous Vehicle Safety & Geofencing Platform
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - autonomous-vehicles
  - geofencing
  - ai
  - safety
home: https://github.com/Trojan3877/AutoGuard-AI-Real-Time-Autonomous-Vehicle-Safety-Geofencing-Platform
maintainers:
  - name: AutoGuard Team
    email: autoguard@example.com
