apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoguard-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoguard
      version: v2
  template:
    metadata:
      labels:
        app: autoguard
        version: v2
