apiVersion: v1
kind: Service
metadata:
  name: autoguard-api
  namespace: autoguard
  labels:
    app: autoguard-api
spec:
  type: ClusterIP
  selector:
    app: autoguard-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
