name: Deploy to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install autoguard ./infra/helm/autoguard
